### ISSUE TITLE
排版错误

### ISSUE THREAD

**Issue by Spdwal** [slegetank/WGEECN#3]
在chapter-4“更强大的正则”一节中的代码
`
(defun update-writestamps ()
  "Find writestamps and replace them with the current time."
  (save-excursion
    (save-restriction
      (save-match-data
        (widen)
        (goto-char (point-min))
        (let ((regexp (concat "^"
                              (regexp-quote writestamp-prefix)
                              "\\(.*\\) "
                              (regexp-quote writestamp-suffix)
                              "$")))
          (while (re-search-forward regexp nil t)
            (replace-match (format-time-string writestamp-format                                                                             (current-time))
                           t t nil 1))))))
  nil)
`
存在显示错误，writestamp-format和(current-time)之间隔了非常长的一段距离，

**Comment by slegetank** [comment]
已修正
