### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Spdwal** [slegetank/WGEECN#4]
第六章递归列表函数中
`
(defun flatten (lst)
  (if (null lst) ; lst是nil吗？
      nil ; 是的话，返回nil
    (if (listp (car lst))
        (append (flatten (car lst))
                (flatten (cdr 1st)))
      (cons (car 1st)
            (flatten (cdr 1st))))))
`
最后三行中的1st应该为lst

**Comment by Spdwal** [comment]
> 第六章递归列表函数中
```(defun flatten (lst) (if (null lst) ; lst是nil吗？ nil ; 是的话，返回nil (if (listp (car lst)) (append (flatten (car lst)) (flatten (cdr 1st))) (cons (car 1st) (flatten (cdr 1st))))))
```
> 最后三行中的1st应该为lst

```
(mapcar '(lambda (x)
           (capitalize x))
        ("lisp" "is" "cool")) -> ("Lisp" "Is" "Cool")
```
其中("lisp" "is" "cool") 应该为 '("lisp" "is" "cool")

**Comment by slegetank** [comment]
已修正
